AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aspire-sam

  Sample SAM Template for aspire-sam

Parameters:
  dbUserPassword:
    NoEcho: true
    Type: String
    Default: 'password'
  dbUserName:
    NoEcho: true
    Type: String
    Default: 'master'
  dbInstanceClass:
    Type: String
    Default: 'db.t2.micro'
  dbInstanceIdentifier:
    Type: String
    Default: 'aspire-db'
  dbName:
    Type: String
    Default: 'main_db'

Globals:
  Function:
    Runtime: python3.6
    Timeout: 3

Resources:
  EmployeeEx:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers/basic-rds
      Handler: app.handler
      Events:
          EmployeeExEvent:
            Type: Api
            Properties:
              Path: /rds-employee-ex
              Method: get

  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '20'
      BackupRetentionPeriod: 7
      CopyTagsToSnapshot: true
      DBInstanceClass: !Ref dbInstanceClass
      DBInstanceIdentifier: !Ref dbInstanceIdentifier
      DBName: !Ref dbName
      EnableCloudwatchLogsExports:
        - postgresql
      EnablePerformanceInsights: true
      Engine: postgres
      EngineVersion: 11.6
      MasterUsername: !Ref dbUserName
      MasterUserPassword: !Ref dbUserPassword
      MaxAllocatedStorage: 1000
      PubliclyAccessible: true
      StorageType: gp2

Outputs:
  EmployeeExApi:
    Description: "API Gateway endpoint URL for Prod stage for EmployeeEx function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/rds-employee-ex/"
  EmployeeEx:
    Description: "EmployeeEx Lambda Function ARN"
    Value: !GetAtt EmployeeEx.Arn
  EmployeeExIamRole:
    Description: "Implicit IAM Role created for EmployeeEx function"
    Value: !GetAtt EmployeeExRole.Arn
