AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aspire-sam

  SAM Template for aspire-sam


Globals:
  Function:
    Runtime: python3.6
    Timeout: 30

Resources:
  CreateDatabaseModels:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/CreateDatabaseModels
      Handler: lambda_function.handler
      Events:
          CreateDatabaseModelsEvent:
            Type: Api
            Properties:
              Path: /create-db-models
              Method: get
      Layers:
        - Ref: CommonDependenciesLayer
  CreateJob:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/CreateJob
      Handler: lambda_function.handler
      Events:
          CreateJobEvent:
            Type: Api
            Properties:
              Path: /createJob
              Method: post
      Layers:
        - Ref: CommonDependenciesLayer
  GetAllJobs:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/GetAllJobs
      Handler: lambda_function.handler
      Events:
          CreateJobEvent:
            Type: Api
            Properties:
              Path: /getAllJobs
              Method: get
      Layers:
        - Ref: CommonDependenciesLayer 
  GetJobById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/GetJobById
      Handler: lambda_function.handler
      Events:
          CreateJobEvent:
            Type: Api
            Properties:
              Path: /getJob/{jobId}
              Method: get
      Layers:
        - Ref: CommonDependenciesLayer 
  DeleteJobById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/DeleteJobById
      Handler: lambda_function.handler
      Events:
          CreateJobEvent:
            Type: Api
            Properties:
              Path: /deleteJob/{jobId}
              Method: get
      Layers:
        - Ref: CommonDependenciesLayer      

  CommonDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: max-aspire-common
      ContentUri: src/layers/database
      CompatibleRuntimes:
        - python3.6
    Metadata:
      BuildMethod: python3.6

Outputs:
  CreateDatabaseModelsApi:
    Description: "API Gateway endpoint URL for Prod stage for CreateDatabaseModels function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/create-db-models/"
  CreateJobApi:
    Description: "API Gateway endpoint URL for Prod stage for CreateJob function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/createJob/"
  GetAllJobsApi:
    Description: "API Gateway endpoint URL for Prod stage for GetAllJobs function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/getAllJobs/"
