AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aspire-sam

  SAM Template for aspire-sam

# Parameters:
#   dbUserPassword:
#     NoEcho: true
#     Type: String
#     Default: 'password'
#   dbUserName:
#     NoEcho: true
#     Type: String
#     Default: 'master'
#   dbInstanceClass:
#     Type: String
#     Default: 'db.t2.micro'
#   dbInstanceIdentifier:
#     Type: String
#     Default: 'aspire-db'
#   dbName:
#     Type: String
#     Default: 'main_db'

Globals:
  Function:
    Runtime: python3.6
    Timeout: 3

Resources:
  CreateDatabaseModels:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/CreateDatabaseModels
      Handler: lambda_function.handler
      Events:
          CreateDatabaseModelsEvent:
            Type: Api
            Properties:
              Path: /create-db-models
              Method: get
      Layers:
        - Ref: CommonDependenciesLayer

  CreateJobApplication:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/JobApplications/CreateJobApplication
      Handler: lambda_function.handler
      Events:
          CreateJobApplicationEvent:
            Type: Api
            Properties:
              Path: /job-applications
              Method: post
      Layers:
        - Ref: CommonDependenciesLayer

  GetAllJobApplications:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/JobApplications/GetAllJobApplications
      Handler: lambda_function.handler
      Events:
          CreateJobApplicationEvent:
            Type: Api
            Properties:
              Path: /job-applications
              Method: get
      Layers:
        - Ref: CommonDependenciesLayer      
        
  DeleteJobApplicationById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/JobApplications/DeleteJobApplicationById
      Handler: lambda_function.handler
      Events:
          CreateJobEvent:
            Type: Api
            Properties:
              Path: /job-applications/{jobAppId}
              Method: delete
      Layers:
        - Ref: CommonDependenciesLayer        

  GetJobApplicationById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/JobApplications/GetJobApplicationById
      Handler: lambda_function.handler
      Events:
          CreateJobEvent:
            Type: Api
            Properties:
              Path: /job-applications/{jobAppId}
              Method: get
      Layers:
        - Ref: CommonDependenciesLayer 

  EditJobApplicationById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/JobApplications/EditJobApplicationById
      Handler: lambda_function.handler
      Events:
          CreateJobEvent:
            Type: Api
            Properties:
              Path: /job-applications/{jobAppId}
              Method: put
      Layers:
        - Ref: CommonDependenciesLayer         
        
  CommonDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: max-aspire-common
      ContentUri: src/layers/database/dependencies/
      CompatibleRuntimes:
        - python3.6

  # AspireDBInstance:
  #   Type: AWS::RDS::DBInstance
  #   Properties:
  #     AllocatedStorage: '20'
  #     BackupRetentionPeriod: 7
  #     CopyTagsToSnapshot: true
  #     DBInstanceClass: !Ref dbInstanceClass
  #     DBInstanceIdentifier: !Ref dbInstanceIdentifier
  #     DBName: !Ref dbName
  #     EnableCloudwatchLogsExports:
  #       - postgresql
  #     EnablePerformanceInsights: true
  #     Engine: postgres
  #     EngineVersion: "11.6"
  #     MasterUsername: !Ref dbUserName
  #     MasterUserPassword: !Ref dbUserPassword
  #     MaxAllocatedStorage: 1000
  #     PubliclyAccessible: true
  #     StorageType: gp2

Outputs:
  CreateDatabaseModelsApi:
    Description: "API Gateway endpoint URL for Prod stage for CreateDatabaseModels function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/create-db-models/"

  JobApplicationsApi:
    Description: "API Gateway endpoints URL for Prod stage for Job Application functions"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/job-applications/"

  JobsApi:
    Description: "API Gateway endpoints URL for Prod stage for Job Application functions"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/jobs/"