AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aspire-sam

  Sample SAM Template for aspire-sam

# Parameters:
#   dbUserPassword:
#     NoEcho: true
#     Type: String
#     Default: 'password'
#   dbUserName:
#     NoEcho: true
#     Type: String
#     Default: 'master'
#   dbInstanceClass:
#     Type: String
#     Default: 'db.t2.micro'
#   dbInstanceIdentifier:
#     Type: String
#     Default: 'aspire-db'
#   dbName:
#     Type: String
#     Default: 'main_db'

Globals:
  Function:
    Runtime: python3.6
    Timeout: 3

Resources:
  CreateDatabaseModels:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/CreateDatabaseModels
      Handler: lambda_function.handler
      Events:
          CreateDatabaseModelsEvent:
            Type: Api
            Properties:
              Path: /create-db-models
              Method: get
      Layers:
        - Ref: CommonDependenciesLayer

  CommonDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: max-aspire-common
      ContentUri: src/layers/database
      CompatibleRuntimes:
        - python3.6
    Metadata:
      BuildMethod: python3.6

  # DBInstance:
  #   Type: AWS::RDS::DBInstance
  #   Properties:
  #     AllocatedStorage: '20'
  #     BackupRetentionPeriod: 7
  #     CopyTagsToSnapshot: true
  #     DBInstanceClass: !Ref dbInstanceClass
  #     DBInstanceIdentifier: !Ref dbInstanceIdentifier
  #     DBName: !Ref dbName
  #     EnableCloudwatchLogsExports:
  #       - postgresql
  #     EnablePerformanceInsights: true
  #     Engine: postgres
  #     EngineVersion: "11.6"
  #     MasterUsername: !Ref dbUserName
  #     MasterUserPassword: !Ref dbUserPassword
  #     MaxAllocatedStorage: 1000
  #     PubliclyAccessible: true
  #     StorageType: gp2

Outputs:
  CreateDatabaseModelsApi:
    Description: "API Gateway endpoint URL for Prod stage for CreateDatabaseModels function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/create-db-models/"
  CreateDatabaseModels:
    Description: "CreateDatabaseModels Lambda Function ARN"
    Value: !GetAtt CreateDatabaseModels.Arn
  CreateDatabaseModelsIamRole:
    Description: "Implicit IAM Role created for CreateDatabaseModels function"
    Value: !GetAtt CreateDatabaseModelsRole.Arn
