AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aspire-sam

  SAM Template for aspire-sam

Parameters:
  dbUserPassword:
    NoEcho: true
    Type: String
    Default: 'password'
  dbUserName:
    NoEcho: true
    Type: String
    Default: 'master'
  dbInstanceClass:
    Type: String
    Default: 'db.t2.micro'
  dbInstanceIdentifier:
    Type: String
    Default: 'aspire-db'
  dbName:
    Type: String
    Default: 'main_db'
  # cognitoUserPool:
  #   Type: String
  #   Default: 'AspireUserPool'
  # cognitoUserPoolArn:
  #   Type: String
  #   Default: ''

Globals:
  Function:
    Runtime: python3.6
    Timeout: 30

Resources:
  # --- Infrastructure ---
  AspireDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '20'
      DBInstanceClass: !Ref dbInstanceClass
      DBInstanceIdentifier: !Ref dbInstanceIdentifier
      DBName: !Ref dbName
      EnableCloudwatchLogsExports:
        - postgresql
      EnablePerformanceInsights: true
      Engine: postgres
      EngineVersion: "11.6"
      MasterUsername: !Ref dbUserName
      MasterUserPassword: !Ref dbUserPassword
      MaxAllocatedStorage: 1000
      PubliclyAccessible: true
      StorageType: gp2

  DatabaseLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: max-aspire-database
      ContentUri: src/layers/database/dependencies/
      CompatibleRuntimes:
        - python3.6

  # AuthLayer:
  #   Type: AWS::Serverless::LayerVersion
  #   Properties:
  #     LayerName: max-aspire-auth
  #     ContentUri: src/layers/auth/dependencies/
  #     CompatibleRuntimes:
  #       - python3.6

  AspireApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      # Auth:
      #   DefaultAuthorizer: !Ref cognitoUserPool
      #   AddDefaultAuthorizerToCorsPreflight: False
      #   Authorizers:
      #     AspireUserPoolTestAuthorizer:
      #       UserPoolArn: !Ref cognitoUserPoolArn

  CreateDatabaseModels:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/CreateDatabaseModels
      Handler: lambda_function.handler
      Events:
          CreateDatabaseModelsEvent:
            Type: Api
            Properties:
              RestApiId: !Ref AspireApi
              Path: /create-db-models
              Method: post
      Layers:
        - Ref: DatabaseLayer
  # --- Infrastructure ---

  # --- Jobs Service ---
  CreateJob:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/Job/CreateJob
      Handler: lambda_function.handler
      Events:
          CreateJobEvent:
            Type: Api
            Properties:
              RestApiId: !Ref AspireApi
              Path: /jobs
              Method: post
      Layers:
        - Ref: DatabaseLayer

  GetAllJobs:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/Job/GetAllJobs
      Handler: lambda_function.handler
      Events:
          CreateJobEvent:
            Type: Api
            Properties:
              RestApiId: !Ref AspireApi
              Path: /jobs
              Method: get
      Layers:
        - Ref: DatabaseLayer

  GetJobById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/Job/GetJobById
      Handler: lambda_function.handler
      Events:
          CreateJobEvent:
            Type: Api
            Properties:
              RestApiId: !Ref AspireApi
              Path: /jobs/{jobId}
              Method: get
      Layers:
        - Ref: DatabaseLayer

  DeleteJobById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/Job/DeleteJobById
      Handler: lambda_function.handler
      Events:
          CreateJobEvent:
            Type: Api
            Properties:
              RestApiId: !Ref AspireApi
              Path: /jobs/{jobId}
              Method: delete
      Layers:
        - Ref: DatabaseLayer

  EditJobById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/Job/EditJobById
      Handler: lambda_function.handler
      Events:
          CreateJobEvent:
            Type: Api
            Properties:
              RestApiId: !Ref AspireApi
              Path: /jobs/{jobId}
              Method: put
      Layers:
        - Ref: DatabaseLayer

  CloseJobById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/Job/CloseJobById
      Handler: lambda_function.handler
      Events:
          CreateJobEvent:
            Type: Api
            Properties:
              RestApiId: !Ref AspireApi
              Path: /jobs/{jobId}/close
              Method: put
      Layers:
        - Ref: DatabaseLayer

  JobContactById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/Job/JobContactById
      Handler: lambda_function.handler
      Events:
          CreateJobEvent:
            Type: Api
            Properties:
              RestApiId: !Ref AspireApi
              Path: /job_contact/{jobId}
              Method: get
      Layers:
        - Ref: DatabaseLayer       
  # --- Jobs Service ---

  # --- Job Applications Service ---
  
  CreateJobApplication:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/JobApplications/CreateJobApplication
      Handler: lambda_function.handler
      Events:
          CreateJobApplicationEvent:
            Type: Api
            Properties:
              RestApiId: !Ref AspireApi
              Path: /job-applications
              Method: post
      Layers:
        - Ref: DatabaseLayer

  GetAllJobApplications:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/JobApplications/GetAllJobApplications
      Handler: lambda_function.handler
      Events:
          CreateJobApplicationEvent:
            Type: Api
            Properties:
              RestApiId: !Ref AspireApi
              Path: /job-applications
              Method: get
      Layers:
        - Ref: DatabaseLayer

  DeleteJobApplicationById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/JobApplications/DeleteJobApplicationById
      Handler: lambda_function.handler
      Events:
          CreateJobEvent:
            Type: Api
            Properties:
              RestApiId: !Ref AspireApi
              Path: /job-applications/{jobAppId}
              Method: delete
      Layers:
        - Ref: DatabaseLayer

  GetJobApplicationById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/JobApplications/GetJobApplicationById
      Handler: lambda_function.handler
      Events:
          CreateJobEvent:
            Type: Api
            Properties:
              RestApiId: !Ref AspireApi
              Path: /job-applications/{jobAppId}
              Method: get
      Layers:
        - Ref: DatabaseLayer

  EditJobApplicationById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/JobApplications/EditJobApplicationById
      Handler: lambda_function.handler
      Events:
          CreateJobEvent:
            Type: Api
            Properties:
              RestApiId: !Ref AspireApi
              Path: /job-applications/{jobAppId}
              Method: put
      Layers:
        - Ref: DatabaseLayer
  # --- Job Applications Service ---

  # --- Industry Tags Service ---
  IndustryTagsCreate:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/IndustryTags/Create
      Handler: lambda_function.handler
      Events:
          CreateJobApplicationEvent:
            Type: Api
            Properties:
              RestApiId: !Ref AspireApi
              Path: /industry-tags
              Method: post
      Layers:
        - Ref: DatabaseLayer

  IndustryTagsGetAll:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/IndustryTags/GetAll
      Handler: lambda_function.handler
      Events:
          CreateJobApplicationEvent:
            Type: Api
            Properties:
              RestApiId: !Ref AspireApi
              Path: /industry-tags
              Method: get
      Layers:
        - Ref: DatabaseLayer

  IndustryTagsGetById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/IndustryTags/GetById
      Handler: lambda_function.handler
      Events:
          CreateJobApplicationEvent:
            Type: Api
            Properties:
              RestApiId: !Ref AspireApi
              Path: /industry-tags/{industryTagId}
              Method: get
      Layers:
        - Ref: DatabaseLayer

  IndustryTagsDeleteById:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/lambda/IndustryTags/DeleteById
      Handler: lambda_function.handler
      Events:
          CreateJobApplicationEvent:
            Type: Api
            Properties:
              RestApiId: !Ref AspireApi
              Path: /industry-tags/{industryTagId}
              Method: delete
      Layers:
        - Ref: DatabaseLayer
        # - Ref: AuthLayer
  # --- Industry Tags Service ---

Outputs:
  Region:
    Description: "Region"
    Value: !Ref AWS::Region

  AspireApiId:
    Description: "Aspire API ID"
    Value: !Ref AspireApi

  AspireApiUrl:
    Description: "Aspire API endpoint URL for Prod environment"
    Value: !Sub 'https://${AspireApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'