name: Dev CD

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: |
          cd ./src/models
          touch .env
          echo "RDS_HOST=$PROD_DB_HOST" >> .env
          echo "RDS_PORT=$PROD_DB_PORT" >> .env
          echo "RDS_USERNAME=$PROD_DB_USERNAME" >> .env
          echo "RDS_PASSWORD=$PROD_DB_PWD" >> .env
          echo "RDS_DB_NAME=$PROD_DB_NAME" >> .env
          echo "STRIPE_KEY=$STRIPE_API_KEY" >> .env
          echo "COGNITO_POOL_ID=$AWS_COGNITO_POOL_ID_PREPROD" >> .env
          cd ../layers/database
          sudo bash database_layer_packages.sh
          sudo chown -R runner dependencies
          sudo chgrp -R docker dependencies
          cd ../auth
          sudo bash auth_layer_packages.sh
          sudo chown -R runner dependencies
          sudo chgrp -R docker dependencies
          cd ../ses_layer
          sudo bash ses_layer_packages.sh
          sudo chown -R runner dependencies
          sudo chgrp -R docker dependencies
          cd ../cognito
          sudo bash cognito_layer_packages.sh
          sudo chown -R runner dependencies
          sudo chgrp -R docker dependencies
          cd ../common
          sudo bash common_layer_packages.sh
          sudo chown -R runner dependencies
          sudo chgrp -R docker dependencies
        env:
          PROD_DB_HOST: ${{secrets.DEV_DB_HOST}}
          PROD_DB_PORT: ${{secrets.DEV_DB_PORT}}
          PROD_DB_USERNAME: ${{secrets.DEV_DB_USERNAME}}
          PROD_DB_PWD: ${{secrets.DEV_DB_PWD}}
          PROD_DB_NAME: ${{secrets.DEV_DB_NAME}}
          STRIPE_API_KEY: ${{secrets.STRIPE_API_KEY}}
      - name: 'Deploy'
        uses: poketapp/gh-action-aws-sam@v2
        env:
          TEMPLATE: 'template.yaml'
          AWS_STACK_NAME: Aspire-Api-Dev
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{secrets.ASPIRE_AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.ASPIRE_AWS_SECRET_ACCESS_KEY}}
          AWS_DEPLOY_BUCKET: aspire-api
          AWS_PARAMETER_OVERRIDES: 'CustomDomainName=services-d.aspire.maxgala.com DbName=${{secrets.DEV_DB_NAME}} DbUserName=${{secrets.DEV_DB_USERNAME}} DbUserPassword=${{secrets.DEV_DB_PWD}} DbInstanceIdentifier=aspire-db-dev'