# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup
        run: |
          touch .env
          echo "RDS_HOST=$PROD_DB_HOST" >> .env
          echo "RDS_PORT=$PROD_DB_PORT" >> .env
          echo "RDS_USERNAME=$PROD_DB_USERNAME" >> .env
          echo "RDS_PASSWORD=$PROD_DB_PWD" >> .env
          echo "RDS_DB_NAME=$PROD_DB_NAME" >> .env
          cat .env
          cd ./src/layers/database
          sudo bash database_layer_packages.sh
          sudo chown -R runner dependencies
          sudo chgrp -R docker dependencies
        env:
          PROD_DB_HOST: ${{secrets.PROD_DB_HOST}}
          PROD_DB_PORT: ${{secrets.PROD_DB_PORT}}
          PROD_DB_USERNAME: ${{secrets.PROD_DB_USERNAME}}
          PROD_DB_PWD: ${{secrets.PROD_DB_PWD}}
          PROD_DB_NAME: ${{secrets.PROD_DB_NAME}}
      - uses: poketapp/gh-action-aws-sam@v2
        env:
          TEMPLATE: 'template.yaml'
          AWS_STACK_NAME: Aspire-Api
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEPLOY_BUCKET: aspire-api
