name: CD

# env:
#     EB_PACKAGE_S3_BUCKET_NAME : "maxcompany"
#     AWS_REGION_NAME           : "us-east-1"


on:
  push:
    branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest           
        steps:
            - name: Git clone our repository
              uses: actions/checkout@v2

            - name: Configure my AWS Credentils
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id    : ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region           : "us-east-1"

            - name: sam build
              uses: youyo/aws-sam-action/python3.6@master
              with: 
                sam_command: build
              env:
                aws-access-key-id    : ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region           : "us-east-1"
                    
            - name: sam deploy
              uses: youyo/aws-sam-action/python3.6@master
              with:
                sam_command: 'deploy --no-fail-on-empty-changeset'
              env:
                    aws-access-key-id    : ${{ secrets.AWS_ACCESS_KEY_ID }}
                    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    aws-region           : "us-east-1"
             
